(ns proflog.kernel.relational-equality-fragment-test
  (:refer-clojure :exclude [==])
  (:require [clojure.core.logic :refer [== run run*]]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [proflog.ast :as ast]
            [proflog.finite-transition-systems :as transition]
            [proflog.gamma :as gamma]
            [proflog.gv-probe :as gv-probe]
            [proflog.kernel.equality-fragment :as equality-fragment]
            [proflog.language :as language]
            [proflog.proof :as proof]))

(def unary-language
  (language/language
    {:constants ['zero]
     :functions {'s 1}
     :relations {'zero-only 1}}))

(def tree-language
  (language/language
    {:constants ['leaf]
     :functions {'node 2}
     :relations {}}))

(defn- zero
  []
  (ast/app-term 'zero))

(defn- s
  [term]
  (ast/app-term 's term))

(defn- leaf
  []
  (ast/app-term 'leaf))

(defn- node
  [left right]
  (ast/app-term 'node left right))

(defn- proposition
  [relation]
  (ast/pos-lit (ast/app-term relation)))

(defn- relational-proofs
  [program formula expected fuel]
  (equality-fragment/prove-program-relational program formula 1 fuel expected))

(deftest relational-gamma-enumerates-closed-terms-without-host-materialization
  (testing "constructor facts are a logic-friendly signature view"
    (is (= [['zero 0] ['s 1]]
           (gamma/constructor-facts unary-language))))
  (testing "unary constructor terms are generated by the relational candidate source"
    (let [source (gamma/relational-candidate-source unary-language 2)]
      (is (= [(zero)
              (s (zero))
              (s (s (zero)))]
             (run* [q]
               (gamma/closed-term-candidateo source q))))))
  (testing "binary constructors stay finite under the depth bound"
    (let [source (gamma/relational-candidate-source tree-language 2)
          depth-one (node (leaf) (leaf))]
      (is (= #{(leaf)
               depth-one
               (node (leaf) depth-one)
               (node depth-one (leaf))
               (node depth-one depth-one)}
             (set
               (run* [q]
                 (gamma/closed-term-candidateo source q)))))
      (is (empty?
            (run 1 [q]
              (== q (node depth-one (node (leaf) depth-one)))
              (gamma/closed-term-candidateo
                (gamma/relational-candidate-source tree-language 2)
                q)))
          "depth-three terms must not leak through a depth-two source"))))

(deftest relational-profile-uses-relational-gamma-and-emits-distinct-evidence
  (let [program (ast/nom x
                  (language/compile-program
                    unary-language
                    [(ast/clause 'zero-only
                                 [x]
                                 (ast/forall-form
                                   x
                                   (ast/neq-lit (ast/var-term x) (zero))))]))
        query (ast/pos-lit (ast/app-term 'zero-only (zero)))]
    (testing "the opt-in route proves failure with a relational profile marker"
      (let [proofs (relational-proofs program query :fails 8)]
        (is (seq proofs))
        (is (proof/contains-step? (first proofs) 'profiled))
        (is (proof/contains-step? (first proofs)
                                  'relational-equality-fragment))
        (is (not (proof/contains-step? (first proofs)
                                       'equality-fragment)))))
    (testing "host equality and host gamma materialization are not used"
      (with-redefs-fn {#'equality-fragment/prove-program-host
                       (fn [& _]
                         (throw (ex-info "host equality-fragment route forbidden"
                                         {})))
                       #'equality-fragment/prove-host
                       (fn [& _]
                         (throw (ex-info "host equality-fragment proof forbidden"
                                         {})))
                       #'equality-fragment/close-branch-result
                       (fn [& _]
                         (throw (ex-info "host branch engine forbidden" {})))
                       #'equality-fragment/unify-term
                       (fn [& _]
                         (throw (ex-info "host unification forbidden" {})))
                       #'equality-fragment/terms-same?
                       (fn [& _]
                         (throw (ex-info "host equality check forbidden" {})))
                       #'equality-fragment/rigid-different?
                       (fn [& _]
                         (throw (ex-info "host rigid disequality forbidden" {})))
                       #'gamma/closed-terms-for-fuel
                       (fn [& _]
                         (throw (ex-info "host gamma materialization forbidden"
                                         {})))}
        #(is (seq (relational-proofs program query :fails 8)))))))

(deftest relational-profile-preserves-shared-universal-witness-discipline
  (testing "ADR-0042's warm/cool disjointness bug does not recur"
    (let [program (ast/nom x
                    (let [vx (ast/var-term x)
                          red (ast/app-term 'red)
                          green (ast/app-term 'green)
                          lang (language/language
                                 {:constants ['red 'green]
                                  :relations {'not-red-or-not-green 0}})]
                      (language/compile-program
                        lang
                        [(ast/clause
                           'not-red-or-not-green
                           []
                           (ast/forall-form
                             x
                             (ast/or-form
                               (ast/neq-lit vx red)
                               (ast/neq-lit vx green))))])))
          query (proposition 'not-red-or-not-green)]
      (is (seq (relational-proofs program query :succeeds 8)))
      (is (empty? (relational-proofs program query :fails 8))
          "failure would require rebinding one universal witness per branch"))))

(deftest relational-profile-covers-full-finite-verifier-parity-set
  (testing "all ADR-0039 group-verifier rows close relationally"
    (doseq [[scenario expected]
            [["z1-full-assoc-truth" :succeeds]
             ["z2-precomputed-assoc-truth" :succeeds]
             ["z2-full-assoc-truth" :succeeds]
             ["non-group-precomputed-assoc" :fails]
             ["non-group-full-assoc" :fails]]]
      (let [{:keys [program relation]} (gv-probe/scenario-config scenario)
            proofs (relational-proofs program (proposition relation) expected 16)]
        (is (seq proofs) scenario)
        (is (proof/contains-step? (first proofs)
                                  'relational-equality-fragment)))))
  (testing "all ADR-0039 transition-system rows close through the same route"
    (doseq [[spec relation expected]
            [[transition/complete-deterministic-spec 'delta-total :succeeds]
             [transition/complete-deterministic-spec 'delta-deterministic :succeeds]
             [transition/incomplete-spec 'delta-total :fails]
             [transition/nondeterministic-spec 'delta-deterministic :fails]]]
      (let [program (transition/transition-program spec)
            proofs (relational-proofs program
                                      (transition/proposition relation)
                                      expected
                                      16)]
        (is (seq proofs) (str (:id spec) "/" relation))
        (is (proof/contains-step? (first proofs)
                                  'relational-equality-fragment))))))

(deftest relational-profile-source-has-no-family-dispatch
  (let [source (slurp "src/proflog/kernel/equality_fragment.clj")]
    (is (not (str/includes? source "gv-probe")))
    (is (not (str/includes? source "finite-transition-systems")))
    (is (not (str/includes? source "hard-family-overlay")))))
